/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreCoteRouteImport } from './routes/sobre-cote'
import { Route as ReservasAbonosCancelacionesRouteImport } from './routes/reservas-abonos-cancelaciones'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PreciosRouteImport } from './routes/precios'
import { Route as PiercingAricaRouteImport } from './routes/piercing-arica'
import { Route as JoyeriaRouteImport } from './routes/joyeria'
import { Route as InformacionSanitariaRouteImport } from './routes/informacion-sanitaria'
import { Route as EvaluacionRouteImport } from './routes/evaluacion'
import { Route as EstudioRouteImport } from './routes/estudio'
import { Route as AtencionMenoresRouteImport } from './routes/atencion-menores'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiciosIndexRouteImport } from './routes/servicios/index'
import { Route as ServiciosPrivadoRouteImport } from './routes/servicios/privado'
import { Route as ServiciosOrejaRouteImport } from './routes/servicios/oreja'
import { Route as ServiciosNarizRostroRouteImport } from './routes/servicios/nariz-rostro'
import { Route as ServiciosLabioBocaRouteImport } from './routes/servicios/labio-boca'
import { Route as ServiciosCuerpoRouteImport } from './routes/servicios/cuerpo'
import { Route as ServiciosSlugRouteImport } from './routes/servicios/$slug'

const SobreCoteRoute = SobreCoteRouteImport.update({
  id: '/sobre-cote',
  path: '/sobre-cote',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasAbonosCancelacionesRoute =
  ReservasAbonosCancelacionesRouteImport.update({
    id: '/reservas-abonos-cancelaciones',
    path: '/reservas-abonos-cancelaciones',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PreciosRoute = PreciosRouteImport.update({
  id: '/precios',
  path: '/precios',
  getParentRoute: () => rootRouteImport,
} as any)
const PiercingAricaRoute = PiercingAricaRouteImport.update({
  id: '/piercing-arica',
  path: '/piercing-arica',
  getParentRoute: () => rootRouteImport,
} as any)
const JoyeriaRoute = JoyeriaRouteImport.update({
  id: '/joyeria',
  path: '/joyeria',
  getParentRoute: () => rootRouteImport,
} as any)
const InformacionSanitariaRoute = InformacionSanitariaRouteImport.update({
  id: '/informacion-sanitaria',
  path: '/informacion-sanitaria',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluacionRoute = EvaluacionRouteImport.update({
  id: '/evaluacion',
  path: '/evaluacion',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudioRoute = EstudioRouteImport.update({
  id: '/estudio',
  path: '/estudio',
  getParentRoute: () => rootRouteImport,
} as any)
const AtencionMenoresRoute = AtencionMenoresRouteImport.update({
  id: '/atencion-menores',
  path: '/atencion-menores',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosIndexRoute = ServiciosIndexRouteImport.update({
  id: '/servicios/',
  path: '/servicios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosPrivadoRoute = ServiciosPrivadoRouteImport.update({
  id: '/servicios/privado',
  path: '/servicios/privado',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosOrejaRoute = ServiciosOrejaRouteImport.update({
  id: '/servicios/oreja',
  path: '/servicios/oreja',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosNarizRostroRoute = ServiciosNarizRostroRouteImport.update({
  id: '/servicios/nariz-rostro',
  path: '/servicios/nariz-rostro',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosLabioBocaRoute = ServiciosLabioBocaRouteImport.update({
  id: '/servicios/labio-boca',
  path: '/servicios/labio-boca',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosCuerpoRoute = ServiciosCuerpoRouteImport.update({
  id: '/servicios/cuerpo',
  path: '/servicios/cuerpo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosSlugRoute = ServiciosSlugRouteImport.update({
  id: '/servicios/$slug',
  path: '/servicios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atencion-menores': typeof AtencionMenoresRoute
  '/estudio': typeof EstudioRoute
  '/evaluacion': typeof EvaluacionRoute
  '/informacion-sanitaria': typeof InformacionSanitariaRoute
  '/joyeria': typeof JoyeriaRoute
  '/piercing-arica': typeof PiercingAricaRoute
  '/precios': typeof PreciosRoute
  '/privacidad': typeof PrivacidadRoute
  '/reservas-abonos-cancelaciones': typeof ReservasAbonosCancelacionesRoute
  '/sobre-cote': typeof SobreCoteRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/servicios/cuerpo': typeof ServiciosCuerpoRoute
  '/servicios/labio-boca': typeof ServiciosLabioBocaRoute
  '/servicios/nariz-rostro': typeof ServiciosNarizRostroRoute
  '/servicios/oreja': typeof ServiciosOrejaRoute
  '/servicios/privado': typeof ServiciosPrivadoRoute
  '/servicios/': typeof ServiciosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atencion-menores': typeof AtencionMenoresRoute
  '/estudio': typeof EstudioRoute
  '/evaluacion': typeof EvaluacionRoute
  '/informacion-sanitaria': typeof InformacionSanitariaRoute
  '/joyeria': typeof JoyeriaRoute
  '/piercing-arica': typeof PiercingAricaRoute
  '/precios': typeof PreciosRoute
  '/privacidad': typeof PrivacidadRoute
  '/reservas-abonos-cancelaciones': typeof ReservasAbonosCancelacionesRoute
  '/sobre-cote': typeof SobreCoteRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/servicios/cuerpo': typeof ServiciosCuerpoRoute
  '/servicios/labio-boca': typeof ServiciosLabioBocaRoute
  '/servicios/nariz-rostro': typeof ServiciosNarizRostroRoute
  '/servicios/oreja': typeof ServiciosOrejaRoute
  '/servicios/privado': typeof ServiciosPrivadoRoute
  '/servicios': typeof ServiciosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atencion-menores': typeof AtencionMenoresRoute
  '/estudio': typeof EstudioRoute
  '/evaluacion': typeof EvaluacionRoute
  '/informacion-sanitaria': typeof InformacionSanitariaRoute
  '/joyeria': typeof JoyeriaRoute
  '/piercing-arica': typeof PiercingAricaRoute
  '/precios': typeof PreciosRoute
  '/privacidad': typeof PrivacidadRoute
  '/reservas-abonos-cancelaciones': typeof ReservasAbonosCancelacionesRoute
  '/sobre-cote': typeof SobreCoteRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/servicios/cuerpo': typeof ServiciosCuerpoRoute
  '/servicios/labio-boca': typeof ServiciosLabioBocaRoute
  '/servicios/nariz-rostro': typeof ServiciosNarizRostroRoute
  '/servicios/oreja': typeof ServiciosOrejaRoute
  '/servicios/privado': typeof ServiciosPrivadoRoute
  '/servicios/': typeof ServiciosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atencion-menores'
    | '/estudio'
    | '/evaluacion'
    | '/informacion-sanitaria'
    | '/joyeria'
    | '/piercing-arica'
    | '/precios'
    | '/privacidad'
    | '/reservas-abonos-cancelaciones'
    | '/sobre-cote'
    | '/servicios/$slug'
    | '/servicios/cuerpo'
    | '/servicios/labio-boca'
    | '/servicios/nariz-rostro'
    | '/servicios/oreja'
    | '/servicios/privado'
    | '/servicios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atencion-menores'
    | '/estudio'
    | '/evaluacion'
    | '/informacion-sanitaria'
    | '/joyeria'
    | '/piercing-arica'
    | '/precios'
    | '/privacidad'
    | '/reservas-abonos-cancelaciones'
    | '/sobre-cote'
    | '/servicios/$slug'
    | '/servicios/cuerpo'
    | '/servicios/labio-boca'
    | '/servicios/nariz-rostro'
    | '/servicios/oreja'
    | '/servicios/privado'
    | '/servicios'
  id:
    | '__root__'
    | '/'
    | '/atencion-menores'
    | '/estudio'
    | '/evaluacion'
    | '/informacion-sanitaria'
    | '/joyeria'
    | '/piercing-arica'
    | '/precios'
    | '/privacidad'
    | '/reservas-abonos-cancelaciones'
    | '/sobre-cote'
    | '/servicios/$slug'
    | '/servicios/cuerpo'
    | '/servicios/labio-boca'
    | '/servicios/nariz-rostro'
    | '/servicios/oreja'
    | '/servicios/privado'
    | '/servicios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtencionMenoresRoute: typeof AtencionMenoresRoute
  EstudioRoute: typeof EstudioRoute
  EvaluacionRoute: typeof EvaluacionRoute
  InformacionSanitariaRoute: typeof InformacionSanitariaRoute
  JoyeriaRoute: typeof JoyeriaRoute
  PiercingAricaRoute: typeof PiercingAricaRoute
  PreciosRoute: typeof PreciosRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ReservasAbonosCancelacionesRoute: typeof ReservasAbonosCancelacionesRoute
  SobreCoteRoute: typeof SobreCoteRoute
  ServiciosSlugRoute: typeof ServiciosSlugRoute
  ServiciosCuerpoRoute: typeof ServiciosCuerpoRoute
  ServiciosLabioBocaRoute: typeof ServiciosLabioBocaRoute
  ServiciosNarizRostroRoute: typeof ServiciosNarizRostroRoute
  ServiciosOrejaRoute: typeof ServiciosOrejaRoute
  ServiciosPrivadoRoute: typeof ServiciosPrivadoRoute
  ServiciosIndexRoute: typeof ServiciosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-cote': {
      id: '/sobre-cote'
      path: '/sobre-cote'
      fullPath: '/sobre-cote'
      preLoaderRoute: typeof SobreCoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas-abonos-cancelaciones': {
      id: '/reservas-abonos-cancelaciones'
      path: '/reservas-abonos-cancelaciones'
      fullPath: '/reservas-abonos-cancelaciones'
      preLoaderRoute: typeof ReservasAbonosCancelacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precios': {
      id: '/precios'
      path: '/precios'
      fullPath: '/precios'
      preLoaderRoute: typeof PreciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piercing-arica': {
      id: '/piercing-arica'
      path: '/piercing-arica'
      fullPath: '/piercing-arica'
      preLoaderRoute: typeof PiercingAricaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joyeria': {
      id: '/joyeria'
      path: '/joyeria'
      fullPath: '/joyeria'
      preLoaderRoute: typeof JoyeriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informacion-sanitaria': {
      id: '/informacion-sanitaria'
      path: '/informacion-sanitaria'
      fullPath: '/informacion-sanitaria'
      preLoaderRoute: typeof InformacionSanitariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluacion': {
      id: '/evaluacion'
      path: '/evaluacion'
      fullPath: '/evaluacion'
      preLoaderRoute: typeof EvaluacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudio': {
      id: '/estudio'
      path: '/estudio'
      fullPath: '/estudio'
      preLoaderRoute: typeof EstudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atencion-menores': {
      id: '/atencion-menores'
      path: '/atencion-menores'
      fullPath: '/atencion-menores'
      preLoaderRoute: typeof AtencionMenoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/': {
      id: '/servicios/'
      path: '/servicios'
      fullPath: '/servicios/'
      preLoaderRoute: typeof ServiciosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/privado': {
      id: '/servicios/privado'
      path: '/servicios/privado'
      fullPath: '/servicios/privado'
      preLoaderRoute: typeof ServiciosPrivadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/oreja': {
      id: '/servicios/oreja'
      path: '/servicios/oreja'
      fullPath: '/servicios/oreja'
      preLoaderRoute: typeof ServiciosOrejaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/nariz-rostro': {
      id: '/servicios/nariz-rostro'
      path: '/servicios/nariz-rostro'
      fullPath: '/servicios/nariz-rostro'
      preLoaderRoute: typeof ServiciosNarizRostroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/labio-boca': {
      id: '/servicios/labio-boca'
      path: '/servicios/labio-boca'
      fullPath: '/servicios/labio-boca'
      preLoaderRoute: typeof ServiciosLabioBocaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/cuerpo': {
      id: '/servicios/cuerpo'
      path: '/servicios/cuerpo'
      fullPath: '/servicios/cuerpo'
      preLoaderRoute: typeof ServiciosCuerpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/$slug': {
      id: '/servicios/$slug'
      path: '/servicios/$slug'
      fullPath: '/servicios/$slug'
      preLoaderRoute: typeof ServiciosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtencionMenoresRoute: AtencionMenoresRoute,
  EstudioRoute: EstudioRoute,
  EvaluacionRoute: EvaluacionRoute,
  InformacionSanitariaRoute: InformacionSanitariaRoute,
  JoyeriaRoute: JoyeriaRoute,
  PiercingAricaRoute: PiercingAricaRoute,
  PreciosRoute: PreciosRoute,
  PrivacidadRoute: PrivacidadRoute,
  ReservasAbonosCancelacionesRoute: ReservasAbonosCancelacionesRoute,
  SobreCoteRoute: SobreCoteRoute,
  ServiciosSlugRoute: ServiciosSlugRoute,
  ServiciosCuerpoRoute: ServiciosCuerpoRoute,
  ServiciosLabioBocaRoute: ServiciosLabioBocaRoute,
  ServiciosNarizRostroRoute: ServiciosNarizRostroRoute,
  ServiciosOrejaRoute: ServiciosOrejaRoute,
  ServiciosPrivadoRoute: ServiciosPrivadoRoute,
  ServiciosIndexRoute: ServiciosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
